### ISSUE TITLE
#1 Subtask : Enhance the current implementation of EasyTest to build framework classes that will allow capturing of Input / Output test data

### ISSUE THREAD

**Issue by anujgandharv** [EaseTech/easytest#10]
This task will involve making the changes to easytest to build a framework level feature for capturing the input/output test data.
the deliverable for this task would be:

1) Create a set of framework classes based on the discussion in #1 and simply test their flow and cohesiveness with the EasyTest framework.

This subtask DOES NOT focus on actually writing the test input/output to a file. Instead it will just introduce framework classes on which the functionality will then be built.

This issue depends on #9

**Comment by ravi-polampelli** [comment]
I have worked on this task, and uploading files for same.  gist of changes in framework
1) Added writeData method in Loader interface, and implemented that method in ExcelDataLoader
2) captured output data in methodCompletesWithParameters method of DataDrivenTest runner class
3) appended output data to map of actual data with "ActualResult" key at appropriate location of map.
4) ExcelDataLoader, overwritten data to spreadsheet, if that particular method's map has "ActualResult"

I still see some issues here to improve upon,
1) The writeData method is called for each method test record, which involves unnecessary i/o. we need to find out the method which will be invoked once for test class, like withAfterClass or getTestRules etc.. and move writeData method to that place
2) method name is appended with class name in DataContext data, but actual data has method name. need to synchronize some how. as of now, i have created another data map with name Actual data and loading values into that once per class.

**Comment by anujgandharv** [comment]
Ravi, your changes are now in the master branch, although while testing locally I am getting null pointer. I am not sure whether it is because of my local changes or otherwise. I will look into it and will let you know. Also, can you please create a WIKI page on git writing how the write functionality works and how a user can write its own custom loader.

Cheers!

**Comment by anujgandharv** [comment]
Ravi, I am past the Null Pointer. I think you forgot to check in the xls file that contains the data for the new method in testExcelDataLoader. I have added that.But I am not able to see the output data in the Excel file. Its not getting written to the file. By debugging, it looks like the output data should be written to the same Excel File that the input test data was being loaded from, but it doesn't appear to be working for me. 
What I have done is I have deployed easytest jar file in Maven as a SNAPSHOT.
Can you download it locally using the maven dependency and see what the problem might be. ?
The Maven dependency is :
&lt;groupId&gt;org.easetech&lt;/groupId&gt;
  &lt;artifactId&gt;easytest&lt;/artifactId&gt;
&lt;version&gt;0.5.0-SNAPSHOT&lt;/version&gt;

**Comment by ravi-polampelli** [comment]
Ya Anuj, I could not edit xls file directly in GitHub, hence I thought of sending that file separately to you. I'll send it soon.
