### ISSUE TITLE
Master src, unable to find easetech.easytest._1 package for XMLdataLoader class

### ISSUE THREAD

**Issue by ravi-polampelli** [EaseTech/easytest#19]
import easetech.easytest._1.Entry;
import easetech.easytest._1.InputTestData;
import easetech.easytest._1.ObjectFactory;
import easetech.easytest._1.TestMethod;
import easetech.easytest._1.TestRecord;

**Comment by anujgandharv** [comment]
Ravi, if you have downloaded the source code, then you first have to build it using Maven(for generating the JAXB classes) as thats what EasyTest supports. The above classes will be available when EasyTest is compiled as a JAR file and is made available from Maven Central Repo.

Cheers!

**Comment by ravi-polampelli** [comment]
Oh! I did maven compile but I commented maven-jaxb2-plugin execution as it was giving some error. let me try it again.

**Comment by anujgandharv** [comment]
Hey Ravi. Did it work for you? I had compiled it using Maven 2.1.0 and everything worked fine.

**Comment by ravi-polampelli** [comment]
I am able to get rid off errors, I still have some questions, 
1) For easytest development perspective, some body like me using eclipse, we see these compilation errors. we need to run mvn build and then copy generated sources back to src folder. Isn't it good idea to keep them in src folder intially it self, also I don't see why we have to generate jaxb sources every time. I think those files can be generated once and kept in src folder and aviod this dynamic generation further.
2) package structure looks bit different, in testDataSchema.xsd, can we add org in namespace, like urn:org:easetech:easytest:1.0

**Comment by anujgandharv** [comment]
Ideally, when you download the source code, you run mvn eclipse:eclipse to create an eclipse project. This command will generate the JAXB classes for you and put it in the target folder which should resolve all compilation problems for you. You should not be copying the classes to your source folder. That's simply wrong and not required.
Finally the classes should not be part of the source control as they are automatically created by the plugin. 

That's a good catch regarding adding org at the front of urn. Will do that. Cheers!

**Comment by ravi-polampelli** [comment]
Ya, you are write about creating eclipse project. lets add that in readme.txt file somewhere. 
I actually did workaround, created maven project in eclipse then copied the src and pom.xml there. 

Still there are some dependencies which are not resolvable, 
1) I had to exclude these in log4j dependency.
<exclusion>
                  <groupId>javax.mail</groupId>
                  <artifactId>mail</artifactId>
                </exclusion>
                <exclusion>
                  <groupId>javax.jms</groupId>
                  <artifactId>jms</artifactId>
                </exclusion>
                <exclusion>
                  <groupId>com.sun.jdmk</groupId>
                  <artifactId>jmxtools</artifactId>
                </exclusion>
                <exclusion>
                  <groupId>com.sun.jmx</groupId>
                  <artifactId>jmxri</artifactId>
                </exclusion>

2) slf4j-api-jdk15-1.6.1.jar is not resolved, I changed it to slf4j-api-1.6.1.jar. 
I did not see any problem with these changes in pom.xml, but anyhow, Pls let me know if these JARs are required and whether we have to add different repositories for these files.

**Comment by anujgandharv** [comment]
Yes. Its actually on my agenda to create a getting started guide for developers who want to contribute to the project. Its that I am simply not getting time for it. I will try to do it this weekend.

I think its a good idea to exclude the JARs that are not resolvable and the list above certainly seems to be the one. There also needs to be a log4j.xml file as otherwise there will be errors on the console about log4j appenders. 

Send me the changes to pom file and I will incorporate it in the main branch.

Cheers!

**Comment by ravi-polampelli** [comment]
Find the attached pom.xml.

**Comment by anujgandharv** [comment]
Ravi, I am not able to see the file. May be you can just check them in the branch , send me a pull request and I can then merge them to the master. It will be easier.
