### ISSUE TITLE
HIGH PRIORITY : Add javadocs for the fields included in the DataDrivenTest

### ISSUE THREAD

**Issue by anujgandharv** [EaseTech/easytest#29]
Please add comprehensive Java docs to all the fields and methods that have been added to the Data Driven Test for supporting Write Loader functionality. 
The Java docs should give clear picture of what the variable is suppose to do and why it is there.

**Comment by ravi-polampelli** [comment]
Yeah, I will do this.

**Comment by anujgandharv** [comment]
Done.
