### ISSUE TITLE
The writeData method is called unnecessarily for each test method.

### ISSUE THREAD

**Issue by ravi-polampelli** [EaseTech/easytest#30]
The writeData method is called for each method test record, which involves unnecessary i/o. we need to find out the method which will be invoked once for test class, like withAfterClass or getTestRules etc.. and move writeData method to that place.

**Comment by anujgandharv** [comment]
Hi Ravi. This is now fixed. The writeData method will now be called once for each test class instead of each test method. I have the code locally working. I will check it in and send it across for your review by tonight or tomorrow.

Cheers!
