### ISSUE TITLE
If I run all the test classes containg my tests at one(using either mvn clean install or any other mechanism), the test data does not get written to the file

### ISSUE THREAD

**Issue by anujgandharv** [EaseTech/easytest#32]
The output test data does not get written to the file in case the tests are run as a unit.

I tried the following scenarios:

1) I right clicked on the src/test/java source folder and selected run as JUnit Test from within my IDE. The tests all run suiccessfully buyt the test data does not get written to the file.
2) When I select only the TestExcelDataLoader class and run it as Junit test, thet est data gets written to the output file.

The same applies with mvn clean install.

**Comment by ravi-polampelli** [comment]
Both those scenarios works fine for me.
Let me checkout the latest code from this branch and check.

**Comment by ravi-polampelli** [comment]
Have you checked in the target/test-classes/testExcelData.xls location?
Can you enable debug logs and send the logs please?

**Comment by anujgandharv** [comment]
So the reason it is happening is because of the following logic:

```
if (!actualDataLoadedOnce) {                   
                actualData = new HashMap<String, List<Map<String, Object>>>(data);
                actualDataLoadedOnce = true;
            }
```

Whats happening is that actualdataLoadedOnce boolean gets reset for every test class. And therefore the actualData contains only the data for the last class and not for all the classes. I have fixed it by removing the if condition altogether and it now works for me.

**Comment by anujgandharv** [comment]
I will check in the code soon and then you can review it.
