### ISSUE TITLE
Excel loader is having problem in loading columns more than first row columns

### ISSUE THREAD

**Issue by ravi-polampelli** [EaseTech/easytest#38]
For e.g: If first row has 3 columns, but if other method has 5 columns

Then excel loader is unable to load those columns, due to countNonEmptyColumns() method in ExcelDataLoader class file.

**Comment by ravi-polampelli** [comment]
I have fixed this issue, by using firstEmptyCellPosition in that row. I will upload it soon for merging

**Comment by ravi-polampelli** [comment]
This issue is fixed. by using column index values.

**Comment by anujgandharv** [comment]
Excellento :)
