### ISSUE TITLE
@AfterClass is executing twice

### ISSUE THREAD

**Issue by ravi-polampelli** [EaseTech/easytest#50]
Looks like @AfterClass is executing twice. please check.

**Comment by anujgandharv** [comment]
I will look into this issue.

**Comment by anujgandharv** [comment]
This is now fixed. The problem was that it was getting called once for the Suite Class (which is DataDrivenTestRunner) and once for JUnitClassRunner (which is EasyTestRunner). We need to only run it at the EasyTestRunner level.
