### ISSUE TITLE
are Spring jars mandatory now to use EasyTest?

### ISSUE THREAD

**Issue by ravi-polampelli** [EaseTech/easytest#53]
Hi Anuj,
I have a query, are Spring jars mandatory now in user project to use EasyTest?
I hope this dependency is not there..

if so,
I think this dependency discourage a few people whose project doesn't depend on Sping at all..
if you think sping jars are mandatory, then I think its better idea to provide EasyTest in different bundles, like core, spring, struts etc...

pls clarify and let me know your views..

Cheers,
Ravi

**Comment by anujgandharv** [comment]
This is already on my mind and I will be creating two projects soon one ofr Core and one for spring. I will keep you posted.

Cheers!

**Comment by ravi-polampelli** [comment]
Yes, now spring module is separated to a another project called easytest-spring.
