### ISSUE TITLE
#1 Subtask : Discuss the design of how to handle gathering the input test data of a test method

### ISSUE THREAD

**Issue by anujgandharv** [EaseTech/easytest#9]
This is a simple task of discussing(with some sort of design/gist links) the issue of how to capture the input as well as output test data of a give executing test method.

The design should focus on making life easier for the end user and therefore the less changes the user has to do in his test class to capture the test data the better it is.

Note: This issue is part of Issue #1

**Comment by ravi-polampelli** [comment]
I started looking into this task and initially looked at, JUnit provided classes like Results, PrintableResults etc.. but all these classes provide some statistics on pass/failure information, but none of them provides actual result (output data) from the test method. Also, I have checked RunListners and RunNotifiers, they talk about the status of the test.

I also tried, sending ActualResult as parameter to Test method, and tried to set the value in Test method, but the value that was set is not returned to JUnit framework because JUnit uses reflection package final parameters, hence values are not passed by reference, hence we are not getting the value back.

I went ahead with following work around (though it is not a neat design):

1) For returning result from test method, we need to have return types for our test methods, hence, we have to change them from void to some other type (say Object or String).
2) As per JUnit core framework there is validation that test methods should have Void and no return types,
3) In EasyTestRunner class, we have overriden that validation in validateTestMethods() 
4) I have commented validatePublicVoid method there, so that JUnit runner returns the Actual Result.
5) then proceed with getting return value from method.invokeExplosively() of methodCompletesWithParameters(). 
6) Used dataLoader.writeData method to write the String value of returned object.
Assumptions : The Object returned from Test Method has overriden toString() method.

Now, We need better design to handle this.

**Comment by anujgandharv** [comment]
Hi Ravi. Although it is a solution, somehow it feels a bit complicated.
What do you think about the following design/solution:

A single annotation on the service that needs to be tested determines whether the test data needs to be persisted. This is all the user needs to know or care about.

Behind the scene, we can use Proxy classes to intercept the test execution and capture the input as well as output test data.
This gives us the following benefits:
1) We do not have to change any current behavior at all.
2) We will not ask the user to return a value for each test method, which will keep it consistent with the JUnit philosophy as well.
3) If a user wants to revert back to JUnit, it would simply mean removing a single annotation from the class and everything will still work.

I tried this solution locally and it works perfectly. 
Here is a simple gist that details the code I wrote : https://gist.github.com/3527709

Let me know what you think about it.

**Comment by ravi-polampelli** [comment]
Anuj,

Its smart solution, but as you also mentioned it looks complicated.
In my view, we should resort last on these dynamic proxies and intruding into JDK Byte code generation activity :)
Of course, it really good finding. 
In my view, my solution looks simpler except that we are breaking the validation of void return type on JUnit test cases (I am not sure anywhere its mentioned in JUnit spec), but any normal Java developer wouldn't mind in mentioning that return type, Isn't it? they can also enhance the result to be written back to file, its purely in user control.

Let us see if we can find better simple solution for this.

I am trying to test your solution, can you let me know where exactly did you inject TestDataInterceptor, I mean which line of EasyTestRunner?

**Comment by anujgandharv** [comment]
HI Ravi,
Sorry to mislead but I mentioned that your solution is a bit complicated :)
Dynamic proxies are actually very powerful and are being used everywhere now a days. Moreover, the solution I proposed resorts to the Proxy pattern of GoF which is one of the most used one in today's world. Spring uses proxies in every step of its usage and thats why we have such a organized, powerful and robust framework.

I discussed the solution of returning result type with a person in JUnit and he said that the reason they did not return the data from the method is because it would have meant uncertainity and more wor for the user.

TestDataInterceptor is being injected  inside enhanceTestSubject method and this method is being called from the constructor of EasyTestRunner after loading the tests.

I still feel strongly about this solution, but I will look and ask around how others do such a thing.

Cheers!

**Comment by ravi-polampelli** [comment]
I agree dynamic proxies are powerful and being used in Spring, Hibernate, EJB3 etc.. but I think they are bit complicated to maintain. Isn't it? 
I din't understand the uncertainity of JUnit test case return type. could you please elaborate?

I have tested your solution, I am not getting Arguments to method as show in your output rather I got below output:
Arguments to method are : [Ljava.lang.Object;@67046704
Did I miss something? 
Its good to separate test running part and proxies to capture the method execution.
I think our idea is to prepare the Output data similar to input data in data structure "Map<String, List<Map<String, Object>>>" 
We can make use of input data from DataContext and append another field called 'ActualResult' and append result to values row. 
But not sure how we can get testMethod name, its input test data field names,which row this results belong to in this solution.

**Comment by anujgandharv** [comment]
Yes. you have to say arg[0].toString() and arg[1].toString() in the methodInterceptor instead of args.toString().

"I think our idea is to prepare the Output data similar to input data in data structure "Map>>" "

Our idea is not that. We don't have to necessarily output the data in Map format since thats the internal structure of EasyTest. We have to output the data in the same format as the user is supplying us(atleast to the point where we can do that). So for e.g.. if the user has supplied data in a CSV file, then we know the structure of CSV file and we can output the data to the File.  As far as getting the name of the fields is concerned, I think I have done that before as well. I will let you know soon.

**Comment by anujgandharv** [comment]
And as you can see from the code I posted, dynamic proxies are actually simpler to write since you do not have to change the behavior. You built around it. Btw, I am coming up with a road map for EasyTest. Is there anything you want to add to that.

**Comment by ravi-polampelli** [comment]
Regarding outputting the data, I meant same thing to maintain the data internally in map and then write it to required file. I'll check roadmap and update you.

**Comment by anujgandharv** [comment]
I am sorry, I got confused. Yes your assumption is correct, We will first be capturing the output data in some sort of internal Data structure(as you said it most probably will be map) and then writing the data out to the file. Although I am not sure exactly how best to do it. But it can be decided once the functionality is actually being written. We will have a better idea then.

**Comment by anujgandharv** [comment]
Ravi, you mentioned that Proxies are a bit complicated to maintain. Do you have any specific reasons to believe this. I ask this because we, in our company, are using Hessian and cglib proxies for more than 4 years now. Our project is SOA based and the service registry and service finding happen through proxies only. And we haven't got any maintenance issues with it. Is there something specific on your mind that I might have missed.

**Comment by ravi-polampelli** [comment]
What you said is absolutely right about proxies.

Regarding maintenance, In my view, less code less worry to maintain it. In my solution there are only two lines of code changing. in your solution, 20 lines and extra cglib.jar required. But as long as it is good design let us proceed with your solution. 
I also looked from user point of view, User anyhow need to mention that he is expecting actual result to be printed, either @TestSubject annotation in your solution or Return type in my solution. In my solution, I thought user has some control to beatify his output. like, he might want to write only count in case of collection output, or he want to write a few important fields in a object etc.. these are just  my thoughts.
As I said, design wise if your solution is looking fine, let us proceed with that.

**Comment by anujgandharv** [comment]
Ravi, would it be possible for you to create a simple gist of your changes and send it across to me. I would like to explore that option as well before writing it off. Somehow, I still do not feel comfortable to ask user to return test data explicitly. But still I would like to at least look at the solution before deciding anything. :)

**Comment by ravi-polampelli** [comment]
Gist of my changes:

1) In TestConditionsSupportedByEasyTestRunner.java
    @Test
    public Item testFindItemsWithReturnType(@Param()
    LibraryId id , @Param(name="itemid") ItemId itemId) {
        System.out.println("library Id : " + id + " and itemId :" + itemId);
        System.out.println("----testFindItemWithoutFileTypeWithStrongParameters started-----");  
        ItemService itemService = new RealItemService();
        Item item = itemService.findItem(id, itemId);
        //actualResult = item.toString();
        System.out.println("return item: " + item.toString());  
        return item;

```
}
```

2) In EasyTestRunner.class

 private Statement methodCompletesWithParameters(
                final FrameworkMethod method, final Assignments complete, final Object freshInstance) {
            return new Statement() {
                @Override
                public void evaluate() throws Throwable {
                    try {
                        final Object[] values= complete.getMethodArguments(
                                true);
                        Object returnObj = method.invokeExplosively(freshInstance, values);
                        //method.invokeExplosively(freshInstance, values);
                        System.out.println("returned object:"+returnObj);
                        for(Object value:values){
                            System.out.println("parameter:"+value);
                        }
                        if(returnObj!=null){
                            dataLoader.writeData(dataFiles[0], returnObj.toString());
                        }
                    } catch (CouldNotGenerateValueException e) {
                        // ignore
                    }
                }
            };
        }

3) In EasyTestRunner.class  
//creating following variables for capturing test output
    private static String[] dataFiles;
    private static Loader dataLoader = null;

**Comment by anujgandharv** [comment]
OK. Let me give it a try and get back to you.

**Comment by anujgandharv** [comment]
Hi Ravi,

So here are my thoughts.

First of all I think using dynamic proxies for returning the data is not an ideal solution and also a different use case than the one you specify here. And so it is out of the picture for this use case.

I agree with you on the part that the solution of returning the data from the test case would not be complicated and should be easy to implement in principle(although somehow I still feel a little apprehensive about it.)

But, I think there are still some design issues with the current proposal that we need to consider before we start with the actual work:

1) We have to consider where to write the data. Which file? Where will this file be stored? Will there be a standard file directory or will that be user specific.

2) What happens in case there is a failure of the test case. In such a scenario, the test method does not return normally and therefore we will not be able to capture the output data. How shall we handle that?

These are my doubts for now. I will update it with more in case I found others.

Let me know what you think of how these situations can be handled and we can move from there.

**Comment by ravi-polampelli** [comment]
Hi Anuj,

My thoughts on your questions:
1) Regarding which file, We can use the same file name and append "-result" and store it in same path as original file
 for e.g. If user has provided ItemServiceTestData.xls at Resources directory, we can output ItemServiceTestData-result.xls in Resources directory. 
2) We might need to capture exception and write Exception in output file.

I tried point 1 earlier, by using WriteData method in Loader interface. I will share the code. Only issue I have seen there is how to determine which row is under test and append the result for each record in Map. Let me try this also and share the code with you.

**Comment by anujgandharv** [comment]
I have a real life situation that might be not ideal for the above scenario. 

We have a structure in our project as follows:
1) a Java project that contains all the test related data and other test utilities, including Spring testing utils, DBUnit testing util classes, liquibase files etc.
2) A service project that depends on my test project. The service project contains my actual integration test classes. These test classes depend on test data files that are present in my test project. So in the scenario as you describe above, we would be required to write a file inside a JAR file? Or we will write the file in the service project with the same path? 

Also, I think it would be a good idea to capture the test data in case there is an assert failure so that the user gets the clear picture of what the input and output was. In case there's an exception, we simply capture the exception and show it to the user. What do you think?

I also have another solution in mind to discuss. How about having a class similar to JUnit's Assert classes.
Something like :

public class AssertClass{

public static save(Object data);

public static save(Object data , String methodName);

public static save(Object data , String methodName , String className);

public static save(Object data , String methodName , String className, String filePath);
}

We always have the methodName in DataContext so it is easily available. The current executing class is also not difficult to get using the getTestClass() static method I believe, and the methodName can be captured in the same manner as JUnit does for a fail assert i think, although I havent looked into it in great detail.

What do you think?

**Comment by anujgandharv** [comment]
With the above solution, we don't have to change any code. Also the user can capture exactly the data he wants to capture and also at what time he wants to capture the data.

**Comment by ravi-polampelli** [comment]
Mate,

My point 2, is same as your explanation on capturing exception. so, I think we both are on same understanding in capturing exception, assert failures, success and actual output data, then write that to a file along with its input data.

I think I did n't quite understand AssertClass solution , can you put gist of changes? or if possible, lets have a quick call. The point that I am not clear mainly is, how in assert class you get output data.

also, I think i din't quite follow your reallife project situation.

**Comment by anujgandharv** [comment]
The difference I see between Exception and assert failure is that an exception normally will occur on the service whereas the assert failure will occur on the test case after the service has returned the data but the returned data is not the expected data. We do not have any control(almost) over the exception as it would be thrown by the service, whereas we ideally should and will have control over the assert failure. Thus in case of Assert Failure, we can still capture the data and present it to the user for his inspection, whereas in case of Exception only the exception will be stored for the user. I will send you the gist in some time as it is a bit busy time in my project. But in the mean time if you have already made the changes according to your suggestion, check it in and send a review across. 

WRT my real life project, the case is :
My test data file resides in a different JAR file than my test cases. How do I handle writing output data and where the output data file will reside?

To be honest, currently I am more comfortable discussing the issues here as it gives me time as well to think and respond. :)

Cheers!

**Comment by ravi-polampelli** [comment]
I am trying to understand the data structure in Map<String, List<Map<String,Object>>>?
For sample.xls file the effective data in the map would be:
Map< getTestData, List<<1,itemId>,<2,libraryId>>,List<<1,11567>,<2,91475>>>
Map<getTestDataWithDouble, List<<1,itemId>,<2,libraryId>>,List<<1,11568>,<2,1>>,List<<1,2>,<2,45>>>
.
.
.
Is my understanding correct?

**Comment by ravi-polampelli** [comment]
I am trying to understand the data structure in Map<String, List<Map<String,Object>>>?
For sample.xls file the effective data in the map would be:
Map< getTestData, List<<1,itemId>,<2,libraryId>>,List<<1,11567>,<2,91475>>>
Map<getTestDataWithDouble, List<<1,itemId>,<2,libraryId>>,List<<1,11568>,<2,1>>,List<<1,2>,<2,45>>>
.
.
.
Is my understanding correct?

**Comment by ravi-polampelli** [comment]
Oh! sorry I misunderstood

Now, I think it would be
For sample.xls file the effective data in the map would be:
Map< getTestData, List<<itemId,11567>,<libraryId,91475>>>
Map<getTestDataWithDouble, List<<itemId,11568>,<libraryId,1>,<itemId,2>,<libraryId,45>>>
.
.
.
Is my understanding correct?

**Comment by anujgandharv** [comment]
So the Data structure works like this :
Map<MethodName , List<Map<MethodAttribute, MethodValue>> which if we take an example of getTestData(libId , itemId) for testData libId=1 , itemId=2 and libId=4,itemId=5 will be :
Map<String,Object> testData1 = new HashMap<String,Object>();
testData1.put(libId , 1);
testData1.put(itemId , 2);
Map<String,Object> testData2 = new HashMap<String,Object>();
testData2.put(libId , 4);
testData2.put(itemId , 5);
Map<getTestData , List<testData1 , testData2>>

I hope its clear now.

**Comment by anujgandharv** [comment]
Well tags have been removed from the comment but I hope it is clear. If not do let me know and I can try again.

**Comment by ravi-polampelli** [comment]
Ok got it.
{getTestData=[{libraryId=91475.0, itemId=11567.0}], getTestDataWithString=[{libraryId=1.0, itemId=12.0}, {libraryId=89.0, itemId=34.0}], getTestDataWithReturnType=[{libraryId=13.0, itemId=11567.0}], getTestDataWithDouble=[{libraryId=1.0, itemId=11568.0}, {libraryId=45.0, itemId=2.0}]}
